### ISSUE TITLE
Incorrect definitions for individuals

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB_owl#32]
Says: A adult fruitless aSP-g (female) neuron expressing that is part of an

It should say: An adult fruitless aSP-g (female) neuron.

http://www.virtualflybrain.org/site/stacks/index.htm?id=VFB_00030743

FlyCircuit ones missing "."
"Definition: A neuron expressing Scer\GAL4[fru.P1.D] that is part of an adult female brain"

http://www.virtualflybrain.org/site/stacks/index.htm?id=VFB_00004655

Matsuo neurons:
Says: "A antennal mechanosensory and motor center AMMC Db7 neuron expressing that is part of an"

It should say: An antennal mechanosensory and motor center AMMC Db7 neuron.

Above are just examples. I didn't check every dataset.

**Comment by dosumis** [comment]
This was (I believe) fixed here:

https://github.com/VirtualFlyBrain/VFB_owl/commit/68500f869b4de6b4d011c3e0554193e4938ef453#diff-cdc63c3134caa5b953936b9bdb10770cL246

Need to check when files were generated.

**Comment by dosumis** [comment]
@Robbie1977 IIRC build now live in tag sets rather than on the repo (or is it both?). Either way, looks like moving to a newer build will fix.

**Comment by Robbie1977** [comment]
Has now been updated on http://vfbsandbox.inf.ed.ac.uk/

**Comment by Robbie1977** [comment]
FYI
http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm?id=VFB_00004655
&
http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm?id=VFB_00030743
Now as requested.

**Comment by mmc46** [comment]
These are still incorrect (fruitless lineage clones):

http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm?id=VFB_00020114

"Definition: An example of an adult fruitless aDT-a lineage clone An example of an adult fruitless aDT-a lineage clone."

There is also information missing about the sex.

http://vfbsandbox.inf.ed.ac.uk/do/individual_list.html?action=exemplar_neuron&id=FBbt:00110414
The top one is female, the bottom one is male. It's not mentioned in the definition. 

Let me know if I need to do something. As far as I can see there isn't a tsv file for this dataset for me to edit.

https://github.com/VirtualFlyBrain/VFB_owl/tree/master/data

**Comment by dosumis** [comment]
The new scala loader fixes this

VFB_00020114
definition "An example of a(n) adult fruitless aDT-a lineage clone that is part of a adult brain."^^xsd:string

(Should be live soon).

Correct reference to sex should be fixed by VirtualFlyBrain/VFB_owl#45
